name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      nim-versions: '["version-2-0", "version-2-2", "devel"]'
      test-command: |
        nimble --version
        nimble install -y
        nimble staticLib
        nimble test
